### PR TITLE
Update to @stytch/react-native v0.8

### PR DESCRIPTION
**Pull request by susie-stytch**
Changes to update to the new `@stytch/react-native` package

### CODE REVIEW

**Comment by nicole-stytch** [comment]
@susie-stytch I'm hitting the following errors while attempting to build using the new instructions in the readme. Do you know what could be causing them?

iOS:
```
The following build commands failed:
	SwiftCompile normal arm64 Compiling\ SessionMigrationHelper.swift /Users/nicole/stytch-public/stytch-react-native-example/node_modules/@stytch/react-native/ios/SessionMigrationHelper.swift (in target 'StytchReactNativeModule' from project 'Pods')
	SwiftCompile normal arm64 /Users/nicole/stytch-public/stytch-react-native-example/node_modules/@stytch/react-native/ios/SessionMigrationHelper.swift (in target 'StytchReactNativeModule' from project 'Pods')
(2 failures)
```

Android:

```
BUILD FAILED in 1m 34s

    at makeError (/Users/nicole/stytch-public/stytch-react-native-example/node_modules/execa/index.js:174:9)
    at /Users/nicole/stytch-public/stytch-react-native-example/node_modules/execa/index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (/Users/nicole/stytch-public/stytch-react-native-example/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:82:7)
    at async Command.handleAction (/Users/nicole/stytch-public/stytch-react-native-example/node_modules/@react-native-community/cli/build/index.js:108:9)
```

Thanks!

**Comment by susie-stytch** [comment]
I'm not too sure what could be causing those errors, but I think I can take a closer look at that iOS error, since it looks like an issue with our `SessionMigrationHelper`. Were there any additional error logs on Android that you could send over?

**Comment by jhaven-stytch** [comment]
@nicole-stytch wanna do a pull and try android again? Looks like on Wednesday Google released a new version of their Jetpack Browser component that's being pulled in by our inapp-browser dependency (because they have a greedy `+` versioning). The most recent commit here should fix it.

I'm also getting the iOS errors and am looking into them now.

**Comment by jhaven-stytch** [comment]
Ok, iOS issue I can fix locally, but it requires editing the generated iOS project (ie: there is no fix to push up). Looking into why this is the case, and why we had no issues during testing.

Basically it's a bridging header issue, where an RN dependency isn't in scope of the Swift code.

**Comment by jhaven-stytch** [comment]
Latest commit is using our forked version of the inappbrowser, which better fixes the Android issue. Still need to figure out iOS issue (SDK-1058)

**Comment by jhaven-stytch** [comment]
@nicole-stytch ok, this should work for both Android and iOS now. Let us know if you run into any issues :)

**Comment by nicole-stytch** [comment]
Confirmed that it's working for me now on both iOS and Android ☺️ thank you!!

**Review by nicole-stytch — APPROVED** [review]

**Pull request merged**
